version: '3.7'
services:
  api:
    image: portfolio2020-api:latest
    environment:
      - ENV=development
      - PORT=4500
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=1234
  db:
    iamge:


