# offline dev only
# environment variables from orchestration would override default environment setup
version: "3.7"
services:

  db:
    image: postgres:13
    restart: always
    # deploy:
    #   restart_policy:
    #     condition: on-failure
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=portfolio
    networks:
      - backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - 5432:5432

  jaeger:
    image: jaegertracing/all-in-one:1.18
    restart: always
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    ports:
     # - 5775:5775/udp # legacy client
     - 6831:6831/udp # accept jaeger.thrift over compact thrift protocol
     - 6832:6832/udp # accept jaeger.thrift over binary thrift protocol
     - 5778:5778 # serve configs
     - 16686:16686 # serve frontend(UI)
     - 14268:14268 # accept jaeger.thrift directly from clients
     - 14250:14250 # accept model.proto
     # - 9411:9411 # Zipkin compatible endpoint (optional)
    networks:
      - backend
  
networks:
  backend:
    driver: overlay
volumes:
  db-data: